<?php
/**
 * @daf-summary Provides client-side form validation by executing rule metadata generated by form components.
 */
?>

<script>

    class DafForms {

        constructor(){
            this.validators = {}
            this.#registerSystemValidators()
        }

        registerValidator(name, callback){
            this.validators[name] = callback
        }
        
        validateForm(form) {
            this.#clearClientErrors(form);

            let isValid = true;
            const summaryErrors = [];

            const fields = form.querySelectorAll("[data-daf-validation-roles]");
            fields.forEach(el => {
                let info;
                try {
                    info = JSON.parse(el.getAttribute("data-daf-validation-roles"));
                } catch {
                    return;
                }

                const rules = info?.rules ?? [];
                const displayName = info.display;
                const fieldPath = el.name
                const value = el.value;

                for (const rule of rules) {
                    const err = this.#validateValue(rule, value, displayName);
                    if (err) {
                        isValid = false;
                        summaryErrors.push({field:fieldPath, msg:err});
                        this.#showClientError(el, fieldPath, err);
                        // stop at first rule failure
                        break;
                    }
                }
            });


            // update summary if exists
            const summaryContainer = form.querySelector('[data-daf-validation-summary]');
            const summary = summaryContainer?.querySelector('ul');
            if (summaryErrors.length > 0 && summary) {
                summary.innerHTML = summaryErrors.map(err => '<li>'+err.msg+'</li>').join('');
                summaryContainer.classList.remove('d-none')
            }

            // You can surface errors however you like here:
            // e.g. add .is-invalid class / show custom message outlet
            return { ok: isValid, errors:summaryErrors };
        }


        #validateValue(rule, value, displayName){
            try {
                let callback = this.validators[rule.name]
                return callback(this, rule, value, displayName)
            } catch (error) {
                throw new Error(`validator for ${rule.name} not exist.!`)
            }
        }

        #showClientError(input, fieldPath, message) {
            let doInvalid = input.getAttribute("data-daf-invalid") ?? null
            if(doInvalid !== null) input.classList.add("is-invalid")
            // If there is a ValidationMessage placeholder, use it
            const form = input.closest("form");
            if (form) {
                const msgEl = form.querySelector(`[data-daf-validation-message="${fieldPath}"]`);
                if (msgEl) {
                    msgEl.textContent = message
                    msgEl.classList.add("d-block")
                    return;
                }
            }
        }
        
        #clearClientErrors(form) {
            // remove invalid class using data-daf-invalid-class when present
            form.querySelectorAll("input.is-invalid").forEach(el => {
                el.classList.remove("is-invalid");
            });

            // clear messages in placeholders
            form.querySelectorAll("[data-daf-validation-message]").forEach(el => {
                el.textContent = "";
                el.classList.remove("d-block");
            });

            // clear summary
            const summaryContainer = form.querySelector("[data-daf-validation-summary]");
            const summary = summaryContainer?.querySelector("ul");
            if (summary) {
                summary.innerHTML = "";
                summaryContainer.classList.add("d-none");
            }
        }

        isEmpty(val) {
            if (val === null || val === undefined) return true;
            if (typeof val === "string") return val.trim() === "";
            if (Array.isArray(val)) return val.length === 0;
            return false;
        }
        
        formatMsg(template, displayName, valueToken) {
            return (template || "")
                .replaceAll("{0}", displayName ?? "")
                .replaceAll("{1}", valueToken ?? "");
        }
        
        #registerSystemValidators(){
            this.registerValidator("required", (dafForms, rule, value, displayName)=>{
                if (dafForms.isEmpty(value)) {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
                return null
            })
            this.registerValidator("notempty", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
                return null
            })
            this.registerValidator("notnull", (dafForms, rule, value, displayName)=>{
                if (value === null || value === undefined) {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
                return null
            })
            this.registerValidator("onlyempty", (dafForms, rule, value, displayName)=>{
                if (!this.isEmpty(value)) {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
                return null
            })
            this.registerValidator("email", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null;
                const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
                if (!emailPattern.test(String(value))) {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
                return null
            })
            this.registerValidator("url", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null
                try {
                    new URL(String(value))
                    return null
                } catch {
                    return this.formatMsg(rule.msgTemplate, displayName, "")
                }
            })
            this.registerValidator("pattern", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null
                try {
                    const re = new RegExp(rule.pattern)
                    if (!re.test(String(value))) {
                        return this.formatMsg(rule.msgTemplate, displayName, rule.pattern)
                    }
                } catch {
                    // if pattern is invalid, skip client validation
                }
                return null
            })
            this.registerValidator("range", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null
                const num = Number(value)

                if (Number.isNaN(num)) return null

                if (num < rule.min) {
                    return this.formatMsg(rule.minMsgTemplate, displayName, rule.min)
                }
                if (num > rule.max) {
                    return this.formatMsg(rule.maxMsgTemplate, displayName, rule.max)
                }
                return null
            })
            this.registerValidator("length", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null;
                const len = String(value).length;

                if (len < rule.min) {
                    return this.formatMsg(rule.minMsgTemplate, displayName, rule.min);
                }
                if (len > rule.max) {
                    return this.formatMsg(rule.maxMsgTemplate, displayName, rule.max);
                }
                return null;
            })
            this.registerValidator("in", (dafForms, rule, value, displayName)=>{
                if (this.isEmpty(value)) return null;
                if (Array.isArray(rule.container)) {
                    if (!rule.container.includes(value)) {
                        return this.formatMsg(rule.msgTemplate, displayName, "");
                    }
                } else if (typeof rule.container === "string") {
                    if (!rule.container.includes(String(value))) {
                        return this.formatMsg(rule.msgTemplate, displayName, "");
                    }
                }
                return null;
            })
        }
    }

    window.DafForms = new DafForms();
</script>
